version: 2.1

orbs:
  docker: circleci/docker@2.4.0

jobs:
  build-and-push:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - docker/login: # ğŸ” Se connecter Ã  Docker Hub
          username: $DOCKER_LOGIN
          password: $DOCKER_PASSWORD
      - docker/build: # ğŸ›  Build de l'image
          image: micks33/my-image
          tag: latest
      - docker/push: # ğŸš€ Push de l'image sur Docker Hub
          image: micks33/my-image
          tag: latest

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-and-push:
          context: docker-hub-creds
